(define (tan-cf x k)
  (define (double-minus-one x)
    (- (* 2 x) 1))
  (define (iter i result)
    (cond ((= i 0) result)
	  ((= i 1) 
	   (iter (- i 1) 
		 (/ x (- 1 result))))
	  (else (iter (- i 1)
		      (/ (* x x) 
			 (- (double-minus-one i) result)))))) 
  (iter k 0))